#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "AnyDesk"
category = "远程连接"
author = "Cno"
url = "https://anydesk.com"

# 指定使用的模板
[template]
scraper = "External"
# resolver = ""
producer = "Click2Install"

# 使用到的正则
[regex]
download_link = 'https:\/\/download\.anydesk\.com(\.cn)?\/AnyDesk\.exe'
download_name = '\.exe'

# 通用参数
[parameter]
build_manifest = ["${taskName}.wcs", "${taskName}/${downloadedFile}"]

# 自动制作模板要求的参数
[producer_required]
shortcutName = "AnyDesk"

# 额外备注
[extra]
require_windows = false
missing_version = "${taskName}/${downloadedFile}"
