#:schema ../../schema/task.json
# 任务基本信息
[task]
name = "Edge"
category = "浏览器"
author = "xrgzs"
url = "https://github.com/bibicadotnet/edge-portable-chrome-next-mini"

# 指定使用的模板
[template]
scraper = "GitHub_Release"
# resolver = ""
producer = "Recursive_Unzip"

# 使用到的正则
[regex]
# download_link = ''
download_name = '^edge-stable-portable-x64_.+\.zip$'
# scraper_version = ''

# 通用参数
[parameter]
# resolver_cd = []
# compress_level = 5
build_manifest = ["${taskName}.wcs", "${taskName}/Edge_Portable/Edge/msedge.exe"]
# build_cover = ""
# build_delete = []

# 爬虫模板临时参数
[scraper_temp]
release_tag_regex = "^edge-stable-portable-x64_"

# 自动制作模板要求的参数
[producer_required]
shortcutName = "Microsoft Edge"
sourceFile = "Edge_Portable/Edge/msedge.exe"
launchArg = "--allow-run-as-system --no-first-run"
recursiveUnzipList = []


# 额外备注
# [extra]
# require_windows = true
# missing_version = ""
# weekly = true
