const PATH_CONFIG = './config.toml',
	LIGHT_TIMEOUT = 30000,
	HEAVY_TIMEOUT = 300000,
	MISSING_VERSION_TRY_DAY = 4;
const PROJECT_ROOT = process.cwd();

export {
	PATH_CONFIG,
	LIGHT_TIMEOUT,
	HEAVY_TIMEOUT,
	PROJECT_ROOT,
	MISSING_VERSION_TRY_DAY,
};
