name: Serve-next

on:
  push:
    branches: [never]
    paths:
      - "src/**"
      - "templates/**"
      - "tasks/**"
      - ".github/**"
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  serve:
    runs-on: windows-2025
    env:
      CLOUD139_TOKEN: ${{ secrets.CLOUD139_TOKEN }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      # 获取仓库源码
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          ref: ${{ github.ref }}

      # 获取rclone
      - uses: actions/checkout@v6
        with:
          repository: Cnotech/rclone
          token: ${{ secrets.RCLONE_TOKEN }}
          path: rclone

      # 取出rclone
      - name: Copy rclone
        run: mv .\rclone\* .\ && New-Item -Path "~/.config/cloud189" -ItemType Directory && mv .\config.json ~/.config/cloud189/config.json

      # 获取并解压 cloud139
      - name: Download and extract cloud139
        uses: robinraju/release-downloader@v1
        with:
          repository: "Cnotech/cloud139"
          latest: true
          fileName: "cloud139-windows-x86_64.zip"
          out-file-path: ./
          extract: true

      # 缓存 node_modules
      - uses: actions/cache@v5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      # 安装 Nodejs
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      # 安装依赖
      - name: Install dependencies
        run: npm install -g pnpm@9 && pnpm install

      - name: Install scoop (Windows)
        uses: MinoruSekine/setup-scoop@v4
        with:
          buckets: main
          apps: innounp

      # 运行构建任务
      - name: Run scripts
        run: pnpm serve -g -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
